os: Visual Studio 2015

# Boost is already installed on AppVeyor.
environment:
  BOOST_ROOT: C:\Libraries\boost_1_81_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_81_0\lib64-msvc-14.0

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 17 2022 Win64" ..
  - cmake --build . --config Release
  - ctest